openapi: '3.0.3'
info:
  title: BGZ opvragen
  version: '0.1.0'
  description: |
    Beschrijving van de endpoints zoals benodigd voor de uitwisseling van de BGZ,
    tussen zorgverleners/toedieners onderling en tussen zorgverleners en PGO.
    Deze endpoints zijn gebaseerd op de FHIR endpoints zoals beschreven op de
    [FHIR website](http://hl7.org/fhir/http.html).

    **Let op**: _deze Swagger beschrijving probeert de workflow weer te geven,
    dus de server kan verschillen bij de individuele paths._

        LET OP: deze versie kan nog fouten bevatten.

servers:
  - url: https://bron.server/fhir/R4/
    description: BGZ-opleverend-systeem
  - url: https://vrager.server/fhir/R4
    description: BGZ-opvragend-systeem
tags:
  - name: Notified-Pull
    description: |
      _Verstuur Task als notificatie_ \
        __Client__ is BGZ-opleverend-systeem. \
        __Server__ is BGZ-opvragend-systeem. 
  - name: BGZ
    description: |
      _Opleveren van BGZ resources_ \
      __Client__ is BGZ-opvragend-systeem. \
      __Server__ is BGZ-opleverend-systeem. 
  - name: PDF/A
    description: |
      _Opleveren van document conform standaard PDF/A_ \
      __Client__ is BGZ-opvragend-systeem. \
      __Server__ is BGZ-opleverend-systeem. 

paths:
  /Task:
    post:
      description: |
        Aanleveren van Task (notified pull). \
        __Client__ is BGZ-opleverend-systeem. \
        __Server__ is BGZ-opvragend-systeem.
      summary: Task aanleveren aan BGZ-opvragend-systeem
      tags:
        - Notified-Pull
      security:
        - create_task:
            - 'user/Task.write'

  /AllergyIntolerance:
    get:
      description: |
        ophalen van de AllergyIntolerance zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen AllergyIntolerance bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/AllergyIntolerance.read'

  /Appointment:
    get:
      description: |
        ophalen van de Appointment zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Appointment bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Appointment.read'

  /Condition:
    get:
      description: |
        ophalen van de Condition zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Condition bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Condition.read'

  /Consent:
    get:
      description: |
        ophalen van de Consent zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Consent bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Consent.read'

  /Coverage:
    get:
      description: |
        ophalen van de Coverage zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Coverage bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Coverage.read'

  /Device:
    get:
      description: |
        ophalen van de Device zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Device bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Device.read'

  /DeviceRequest:
    get:
      description: |
        ophalen van de DeviceRequest zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen DeviceRequest bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/DeviceRequest.read'

  /DeviceUseStatement:
    get:
      description: |
        ophalen van de DeviceUseStatement zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen DeviceUseStatement bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/DeviceUseStatement.read'

  /Encounter:
    get:
      description: |
        ophalen van de Encounter zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Encounter bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Encounter.read'

  /Flag:
    get:
      description: |
        ophalen van de Flag zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Flag bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Flag.read'

  /Immunization:
    get:
      description: |
        ophalen van de Immunization zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Immunization bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Immunization.read'

  /ImmunizationRecommendation:
    get:
      description: |
        ophalen van de ImmunizationRecommendation zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen ImmunizationRecommendation bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/ImmunizationRecommendation.read'

  /MedicationDispense:
    get:
      description: |
        ophalen van de MedicationDispense zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen MedicationDispense bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/MedicationDispense.read'

  /MedicationRequest:
    get:
      description: |
        ophalen van de MedicationRequest zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen MedicationRequest bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/MedicationRequest.read'

  /MedicationStatement:
    get:
      description: |
        ophalen van de MedicationStatement zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen MedicationStatement bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/MedicationStatement.read'

  /NutritionOrder:
    get:
      description: |
        ophalen van de NutritionOrder zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen NutritionOrder bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/NutritionOrder.read'

  /Observation:
    get:
      description: |
        ophalen van de Observation zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Observation bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Observation.read'

  /Organization:
    get:
      description: |
        ophalen van de Organization zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Organization bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Organization.read'

  /Patient:
    get:
      description: |
        ophalen van de Patient zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Patient bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Patient.read'

  /Practitioner:
    get:
      description: |
        ophalen van de Practitioner zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Practitioner bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Practitioner.read'  

  /PractitionerRole:
    get:
      description: |
        ophalen van de PractitionerRole zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen PractitionerRole bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/PractitionerRole.read'  

  /Procedure:
    get:
      description: |
        ophalen van de Procedure zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Procedure bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Procedure.read'  

  /ProcedureRequest:
    get:
      description: |
        ophalen van de ProcedureRequest zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen ProcedureRequest bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/ProcedureRequest.read'

  /Specimen:
    get:
      description: |
        ophalen van de Specimen zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Specimen bij BGZ-opleverend-systeem
      tags:
        - BGZ
      security:
        - get_bgz:
          - 'patient/Specimen.read'  

  /Document:
    get:
      description: |
        ophalen van de Document zib op basis van de query zoals beschreven in de Notified-Pull Task.

        __Client__ is BGZ-opvragend-systeem. \
        __Server__ is BGZ-opleverend-systeem. 

      summary: Opvragen Document bij BGZ-opleverend-systeem
      tags:
        - PDF/A
      security:
        - get_bgz:
          - 'patient/Document.read'



components:
  securitySchemes:
    create_task:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.test.server/v1/oauth/authorize'
          scopes:
            'user/Task.write': create Task

    get_bgz:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.test.server/v1/oauth/authorize'
          scopes:
            'patient/AllergyIntolerance.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Appointment.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Condition.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Consent.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0 
            'patient/Coverage.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Device.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/DeviceRequest.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/DeviceUseStatement.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Encounter.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Flag.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Immunization.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/ImmunizationRecommendation.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/MedicationDispense.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/MedicationRequest.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/MedicationStatement.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/NutritionOrder.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Observation.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Organization.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Patient.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Practitioner.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/PractitionerRole.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Procedure.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/ProcedureRequest.read': Onderdeel van Verzamelen Basisgegevens zorg 3.0
            'patient/Document.read':  Onderdeel van PDF/A