openapi: '3.0.3'
info:
  version: 0.0.4
  title: Adressering Server
  description: |
    Aorta Adressering Server API

        LET OP: deze versie kan nog fouten bevatten.


externalDocs:
  description: Project documentatie zie confluence
  url: https://public.vzvz.nl/display/UBEBVLEL/Adressering+Server+Interfaces+-+0.7.x

servers: 
  - url: https://localhost/1.0.0/api/adresseringservice
    description: Dev server
  - url: https://test.server/1.0.0/api/adresseringservice
    description: Test en acceptatie server

security:
  - OAuth2:
      - readOnly

tags:
  - name: ''

paths:
  /getRoutingInfo:
    post:
      tags:
        - ''
      operationId: getRoutingInfo
      summary: Opleveren van informatie over welke applicaties een gewenste interactie ondersteunen en hoe deze geïnitieerd moeten worden
      description: Het doel van de Adressering Server is het opleveren van informatie over welke applicaties een gewenste interactie ondersteunen en over de wijze waarop die interactie vervolgens kan worden geïnitieerd. Hierbij wordt rekening gehouden met eventuele, voor de betreffende applicaties beschikbare, transformaties.
      parameters:        
        - $ref: '#/components/parameters/AORTA-ID'
      requestBody:
        description: |
          Lijst met destinations en interacties
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/RoutingInfoRequest'
            examples:
              routingInfoReqMedMij:
                $ref: '#/components/examples/routingInfoReqMedMij'
              routingInfoReqAorta:
                $ref: '#/components/examples/routingInfoReqAorta'
              routingInfoReqAuthServer-ZA:
                $ref: '#/components/examples/routingInfoReqAuthServer-ZA'
              
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        406:
          $ref: '#/components/responses/406'
        415:
          $ref: '#/components/responses/415'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/400'

components:
  parameters:
    AORTA-ID:
        $ref: 'components/parameters/aorta-tokens.yml#/AORTA-ID'

  schemas:
    AORTA-ID:
      $ref: 'components/schemas/aorta-tokens.yml#/AORTA-ID'
    
    RoutingInfoRequest:
      $ref: 'components/schemas/RoutingInfoRequest.yml#/RoutingInfoRequest'

    RoutingInfoResponse:
      $ref: 'components/schemas/RoutingInfoResponse.yml#/RoutingInfoResponse'

  responses:
    200:
      description: |
        OK

        Deze objecten worden geretourneerd in de volgorde waarin de betreffende 
        interactions werden ontvangen in het getRoutingInfo request.
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/RoutingInfoResponse'
          examples:
            routingInfoResMedMij:
              $ref: '#/components/examples/routingInfoResMedMij'
            routingInfoResAorta:
              $ref: '#/components/examples/routingInfoResAorta'
            routingInfoResAuthServer-ZA:
              $ref: '#/components/examples/routingInfoResAuthServer-ZA'

    400:
      description: |
        Ongeldig verzoek (voldoet niet aan de interface specificatie), 
        ook wanneer interactie-id niet kan worden bepaald

    401:
      description: Unauthorized
    403:
      description: |
        Forbidden

        Client beschikt niet over de juiste autorisatie
    406:
      description: Not Acceptable
    415:
      description: Unsupported Media Type
    429:
      description: Too Many Requests
    500:
      description: Fout in server

  examples:
    routingInfoReqMedMij:
      summary: Interactie vanuit MedMij
      value: |-
        {
          "destination": {
            "code": "382",
            "codeSystem": "urn:oid:2.16.528.1.1007.3.3"
          },
          "interaction": [{
            "id": "create:Observation:1.0:request"
          }]
        }
    routingInfoReqAorta:
      summary: Initiatie vanuit GBx-client
      value: |-
        {
          "destination": {
              "code": "592",
              "codeSystem": "urn:oid:2.16.528.1.1007.3.3"
          },
          "interaction": [{
              "method": "GET",
              "url": "3287/MedicationRequest/23483147812",
              "aortaVersion": "1.0"
          }, {
              "method": "GET",
              "url": "4001/MedicationRequest/23483147813",
              "aortaVersion": "2.0"
          }, {
              "id": "search:Appointment:1.0:request"
          }]
        }
    routingInfoReqAuthServer-ZA:
      summary: Aanroep vanuit Autorisatie Server ZA
      value: |-
        {
          "destination": {
            "code": "3287",
            "codeSystem": "urn:oid:2.16.840.1.113883.2.4.6.6"
          },
          "interaction": [{
            "id": "search:MedicationRequest:1.0:request"
          }]
        }

    routingInfoResMedMij:
      summary: Response aan MedMij
      value: |-
        [{
          "interactionId": "create:Observation:1.0:request",
          "destinationInfo": [{
            "destination": {
              "code": "5476",
              "codeSystem": "urn:oid:2.16.840.1.113883.2.4.6.6"
            },
            "fqdn": "bron.zorgaanbieder.nl",
            "transformationId": "1"
          }]
        }]

    routingInfoResAorta:
      summary: Response aan GBx-client
      value: |-
        [{
          "interactionId": "read:MedicationRequest:1.0:request",
          "destinationInfo": [{
            "destination": {
              "code": "3287",
              "codeSystem": "urn:oid:2.16.840.1.113883.2.4.6.6"
            },
            "fqdn": "bron-1.zorgaanbieder.nl"
          }]
        }, {
          "interactionId": "read:MedicationRequest:2.0:request"
        }, {
          "interactionId": "search:Appointment:1.0:request",
          "destinationInfo": [{
              "destination": {
                "code": "3288",
                "codeSystem": "urn:oid:2.16.840.1.113883.2.4.6.6"
              },
              "fqdn": "bron-2.zorgaanbieder.nl",
              "transformationId": "3"
          }]
        }]
    routingInfoResAuthServer-ZA:
      summary: Response aan Autorisatie Server ZA
      value: |-
        [{
          "interactionId": "search:MedicationRequest:1.0:request",
          "destinationInfo": [{
              "destination": {
                "code": "3287",
                "codeSystem": "urn:oid:2.16.840.1.113883.2.4.6.6"
              },
              "fqdn": "bron-1.zorgaanbieder.nl"
          }]
        }]

  securitySchemes:    
    OAuth2:
          type: oauth2
          flows:
            authorizationCode:
              scopes:
                readOnly: read objects in your account
              authorizationUrl: 'https://example.com/oauth/authorize'
              tokenUrl: 'https://example.com/oauth/token'